language: objective-c
xcode_workspace: HaidoraBase.xcworkspace
xcode_scheme: HaidoraBase
xcode_sdk: iphonesimulator
install: 
  - cd Project/HaidoraBase/
  - pod install
script:
  - xctool -workspace HaidoraBase.xcworkspace -scheme HaidoraBase -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
